version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: uai_pharma_db
    volumes:
      - db:/home/uai_pharma/db
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

  python:
    image: python:3.8
    container_name: uai_pharma_interpreter
    working_dir: /usr/src/meu_site
    tty: true
    stdin_open: true
    command: python3

  web:
    build: .
    container_name: uai_pharma
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - main:/home/uai_pharma/main
    ports:
      - "8000:8000"
    depends_on:
      - db
      - python
volumes:
  db:
  main: