# Generated by Django 3.2.6 on 2021-08-26 15:28

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210826_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='', max_length=10, validators=[authentication.models.regexTelefone], verbose_name='Número de Telefone'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=50, validators=[authentication.models.regexAlfabetico], verbose_name='Rua')),
                ('bairro', models.CharField(max_length=50, validators=[authentication.models.regexAlfabetico], verbose_name='Bairro')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
