# Generated by Django 3.2.6 on 2021-08-28 23:28

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210826_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=50, validators=[authentication.models.regexAlfabetico], verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[authentication.models.UnicodeUsernameValidator], verbose_name='Primeiro nome'),
        ),
    ]
