# Generated by Django 3.2.6 on 2021-08-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210828_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nome_social',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
