# Generated by Django 3.2.6 on 2021-08-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_nome_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nome_social',
        ),
    ]
