# Generated by Django 3.2.6 on 2021-08-29 01:16

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_nome_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=50, validators=[authentication.models.regexAlfabetico()], verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=50, validators=[authentication.models.regexAlfabetico()], verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=50, validators=[authentication.models.regexAlfabetico()], verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[authentication.models.regexAlfabetico()], verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[authentication.models.UnicodeUsernameValidator()], verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(max_length=10, validators=[authentication.models.regexTelefone()], verbose_name='Número de Telefone'),
        ),
    ]
