# Generated by Django 3.2.6 on 2021-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(to='shopping.Tag'),
        ),
    ]
