# Generated by Django 3.2.6 on 2021-08-26 15:28

from django.db import migrations, models
import shopping.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210826_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='promocao',
            field=models.IntegerField(validators=[shopping.validators.validate_range], verbose_name='Valor da promoção (%)'),
        ),
    ]
