# Generated by Django 3.2.6 on 2021-08-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_produto_promocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.produto')),
            ],
        ),
    ]
